---
name: PR

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  Commits:
    name: Conventional Commits
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.yml
